# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: imperfectproduce/node-aws-cli:carbon-1.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.1-ce
      - run:
          name: Authenticate with Github Packages
          command: echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Tests
          command: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with Github Packages
          command: echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish
  security_audit:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Check for security vulnerabilities in dependencies
          # https://classic.yarnpkg.com/en/docs/cli/audit/
          # yarn audit exit code sums each type of severity that exist
          # this will fail if HIGH or CRITICAL serverities exist
          command: |
              set +e
              yarn audit --level high
              if [ $? -gt 7 ]; then exit 1; else exit 0; fi

workflows:
  version: 2
  security_audit:
    jobs:
      - security_audit:
          filters:
              branches:
                ignore: master
  build-deploy:
    jobs:
      - build:
          context: github
          filters:
            tags:
              only: /.*/
      - publish:
          context: github
          requires:
            - build
          filters:
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)$/
            branches:
              ignore: /.*/
