# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: imperfectproduce/node-aws-cli:carbon-1.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.1-ce
      # - run:
      #     name: Clear Yarn Cache (temp)
      #     command: yarn cache clean
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Tests
          command: yarn test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
